### ISSUE TITLE
Create shopping cart interface

### ISSUE THREAD

**Issue by uo276077** [Arquisoft/dede_en3b#46]
## Tasks to do:
 

- [x] Create individual view for a product
- [x] Link individual view with catalogue using routes
- [x] Save a product in the shopping cart when clicking on “add to cart”
- [x] Create shopping cart view
- [x] Add login functionality (access pod)
